---
title: "WGCNA analysis of HNSCC TCGA data"
author: "Bernard Lee"
date: "2020-10-20"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

#### Please refer to this link: https://bioconductor.riken.jp/packages/3.4/bioc/vignettes/CVE/inst/doc/WGCNA_from_TCGA_RNAseq.html

#### Load library
```{r}
library(tidyverse)
```

#### Step 1: Preprocessing of TCGA RNAseq data
```{r}
RNAseq <- HNSCC_CLEAN
RNAseq <- RNAseq[apply(RNAseq, 1, function(x) sum(x == 0)) < ncol(RNAseq)*0.8, ]
RNAseq_metadata <- HNSCC_metadata

# Normalization
library(limma)
RNAseq_voom <- voom(RNAseq)$E

# Transpose matrix to correlate genes
WGCNA_matrix <- t(RNAseq_voom[order(apply(RNAseq_voom, 1, mad), decreasing = TRUE)[1:5000], ])
```

#### Step 2: Construction of co-expression network
```{r}
# similarity measure between gene profiles: biweight midcorrelation
library(WGCNA)
s <- abs(bicor(WGCNA_matrix))

powers <- c(c(1:10), seq(from = 12, to = 20, by = 2))
sft <- pickSoftThreshold(WGCNA_matrix, powerVector = powers, verbose = 5)
par(pty = "s")
plot(sft$fitIndices[, 1], -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2], xlab = "Soft Threshold (power)", ylab = "Scale Free Topology Model Fit, signed R^2", type = "n", main = paste("Scale independence"))
text(sft$fitIndices[, 1], -sign(sft$fitIndices[, 3]) * sft$fitIndices[,2], labels = powers, cex = 1, col = "red")
abline(h = 0.90, col = "red")

# calculation of adjacency matrix
# Change the value of beta accordingly to the soft threshold power
beta <- 5
a <- s^beta

# dissimilarity measure
w <- 1 - a
```

#### Step 3: Identification of co-expression modules
```{r}
# Create gene tree by average linkage hierarchical clustering
geneTree <- hclust(as.dist(w), method = "average")

# Module identification using dynamic tree cut algorithm
modules <- cutreeDynamic(dendro = geneTree, distM = w, deepSplit = 4, pamRespectsDendro = FALSE, minClusterSize = 30)

# Assign module colours
module.colours <- labels2colors(modules)

# Plot the dendrogram and corresponding colour bars underneath
plotDendroAndColors(geneTree, module.colours, "Module colours", dendroLabels = FALSE, hang = 0.03, addGuide = TRUE, guideHang = 0.05, main = "")

library(ape)

# Calculate eigen genes
MEs <- moduleEigengenes(WGCNA_matrix, colors = module.colours, excludeGrey = FALSE)$eigengenes

# Calculate dissimilarity pf module genes
MEDiss <- 1 - cor(MEs)

# Cluster module eigengenes
METree <- hclust(as.dist(MEDiss), method = "average")

# Plot the result with phytools package
par(mar = c(2, 2, 2, 2))
plot.phylo(as.phylo(METree), type = "fan", show.tip.label = FALSE, main = "")
tiplabels(frame = "circle", col = "black", text = rep("", length(unique(modules))), bg = levels(as.factor(module.colours)))
```

#### Step 4: Relation of co-expression modules to sample traits
```{r}

```


#### Session info
```{r}
sessionInfo()
```















